# frozen_string_literal: true

def replace_all(path, replacements)
  text = File.read(path, encoding: "UTF-8")
  replacements.each do |from, to|
    text.gsub!(from, to)
  end
  File.write(path, text, mode: "w:UTF-8")
end

ROOT = "/Users/mada/Documents/Playground/marand-client-preview"

common_rewire = [
  ["marand-wireframes.html", "marand-wireframes-ro.html"],
  ["marand-products.html", "marand-products-ro.html"],
  ["marand-gallery.html", "marand-gallery-ro.html"],
  ["marand-quote.html", "marand-quote-ro.html"]
]

replace_all("#{ROOT}/index-ro.html", [
  ['<html lang="en">', '<html lang="ro">'],
  ['url=./marand-wireframes.html', 'url=./marand-wireframes-ro.html'],
  ['window.location.replace("./marand-wireframes.html");', 'window.location.replace("./marand-wireframes-ro.html");'],
  ["Marand Client Preview", "Previzualizare client Marand"],
  ["Redirecting to the client preview.", "Redirecționare către previzualizarea pentru client."],
  ['<a href="./marand-wireframes.html">Open the wireframe</a>.', '<a href="./marand-wireframes-ro.html">Deschide wireframe-ul</a>.']
])

replace_all("#{ROOT}/marand-wireframes-ro.html", common_rewire + [
  ['<html lang="en">', '<html lang="ro">'],
  ["<title>Marand — Print Shop Wireframes</title>", "<title>Marand — Wireframe Tipografie</title>"],
  ["Press G to toggle grid", "Apasă G pentru grid"],
  [">Home<", ">Acasă<"],
  [">Products<", ">Produse<"],
  [">How It Works<", ">Cum funcționează<"],
  [">Gallery<", ">Galerie<"],
  [">Equipment<", ">Echipamente<"],
  [">About<", ">Despre<"],
  [">Request a Quote<", ">Cere ofertă<"],
  ["Screen 1 — Home · 12-col grid", "Ecran 1 — Acasă · grid 12 coloane"],
  ["Large Format Print Shop", "Tipografie large format"],
  ["Your vision.<br>Printed bold", "Viziunea ta.<br>Printată cu impact"],
  ["Banners, canvas, stickers, mesh, textiles — from small runs to large format. Professional printing with fast turnaround and vibrant color.", "Bannere, canvas, stickere, mesh, textile — de la tiraje mici la formate mari. Print profesional cu termen rapid și culori vibrante."],
  [">Browse Products<", ">Vezi produsele<"],
  [">Get a Quote<", ">Cere ofertă<"],
  ["Hero Image — Shop / Large Print", "Imagine hero — shop / print mare"],
  ["Large Format Prints", "Printuri large format"],
  ["Banners & Mesh", "Bannere și mesh"],
  ["Canvas Prints", "Printuri pe canvas"],
  ["Stickers & Vinyl", "Stickere și vinyl"],
  ["T-Shirts & Textiles", "Tricouri și textile"],
  ["Flyers & Cards", "Flyere și cărți de vizită"],
  ["Orders Completed", "Comenzi finalizate"],
  ["Fast Turnaround", "Execuție rapidă"],
  ["Pro Machines", "Echipamente profesionale"],
  ["Max Print Width", "Lățime maximă de print"],
  ["Screen 2 — Products · 12-col grid", "Ecran 2 — Produse · grid 12 coloane"],
  ["What We Print", "Ce printăm"],
  ["Everything you need, printed to perfection", "Tot ce ai nevoie, printat impecabil"],
  ["From a single sticker to a 10-meter banner — we handle it all with professional equipment and premium materials.", "De la un singur sticker până la un banner de 10 metri — realizăm totul cu echipamente profesionale și materiale premium."],
  ["Best Seller", "Cel mai vândut"],
  ["Indoor + Outdoor", "Interior + exterior"],
  ["Cut + Printed", "Decupat + printat"],
  ["From 1 piece", "De la 1 bucată"],
  ["Posters, photo enlargements, art reproductions, and signage up to 134cm wide.", "Postere, fotografii mărite, reproduceri de artă și semnalistică până la 134 cm lățime."],
  ["Vinyl banners, mesh banners, roll-up displays, and PVC flex for any environment.", "Bannere din vinyl, mesh, roll-up-uri și PVC flex pentru orice spațiu."],
  ["Gallery-quality canvas prints stretched on wooden frames for art and decor.", "Printuri pe canvas de calitate gallery, întinse pe rame din lemn pentru artă și decor."],
  ["Die-cut stickers, vinyl decals, window graphics, and vehicle lettering.", "Stickere decupate, autocolant vinyl, grafică pentru vitrine și litere pentru vehicule."],
  ["Custom t-shirts, bags, caps, and workwear — vibrant colors on any fabric.", "Tricouri, sacoșe, șepci și haine de lucru personalizate — culori vibrante pe orice material textil."],
  ["Business cards, flyers, brochures, menus — fast laser printing.", "Cărți de vizită, flyere, broșuri, meniuri — print laser rapid."],
  ["Popular Products", "Produse populare"],
  ["Vinyl Banner", "Banner din vinyl"],
  ["440g PVC, full color, hemmed & eyeleted", "PVC 440g, full color, tivuit și cu capse"],
  ["Stretched Canvas", "Canvas întins pe ramă"],
  ["Premium cotton canvas, wood frame included", "Canvas premium din bumbac, ramă din lemn inclusă"],
  ["Die-Cut Stickers", "Stickere decupate"],
  ["Custom shape, weatherproof vinyl, laminated", "Formă personalizată, vinyl rezistent la exterior, laminat"],
  ["Custom T-Shirt", "Tricou personalizat"],
  ["DTF print, any color fabric, wash-resistant", "Print DTF, pe orice culoare de material, rezistent la spălare"],
  ["Screen 3 — How It Works · 12-col grid", "Ecran 3 — Cum funcționează · grid 12 coloane"],
  ["Simple Process", "Proces simplu"],
  ["From file to finished product in 4 steps", "De la fișier la produsul final în 4 pași"],
  ["Whether you order online or visit our shop, the process is quick and straightforward.", "Fie că plasezi comanda online sau vii în shop, procesul este rapid și clar."],
  ["Choose Product", "Alege produsul"],
  ["Pick your product type, size, material, and quantity from our catalog.", "Alege tipul de produs, dimensiunea, materialul și cantitatea din catalog."],
  ["Upload Design", "Încarcă designul"],
  ["Send your print-ready file or let us help you prepare the artwork.", "Trimite fișierul pregătit pentru print sau lasă-ne să te ajutăm cu grafica."],
  ["We Print & Finish", "Printăm și finisăm"],
  ["Your order is printed, cut, laminated, or pressed — with quality checks at every step.", "Comanda ta este printată, tăiată, laminată sau presată — cu verificări de calitate la fiecare pas."],
  ["Pick Up or Deliver", "Ridicare sau livrare"],
  ["Collect from our shop or we ship directly to you. Fast turnaround guaranteed.", "Ridici din shop sau livrăm direct la tine. Termen rapid garantat."],
  ["Supported File Formats", "Formate de fișiere acceptate"],
  ["For best results, send vector files (PDF, AI, EPS) or high-resolution images (300 DPI minimum). CMYK color mode preferred.", "Pentru cele mai bune rezultate, trimite fișiere vectoriale (PDF, AI, EPS) sau imagini de înaltă rezoluție (minimum 300 DPI). Preferăm modul de culoare CMYK."],
  ["Available Materials", "Materiale disponibile"],
  ["Photo paper (glossy/matte)", "Hârtie foto (lucioasă/mată)"],
  ["Screen 4 — Gallery · 12-col grid", "Ecran 4 — Galerie · grid 12 coloane"],
  ["Our Work", "Lucrările noastre"],
  ["Recent projects", "Proiecte recente"],
  [">All<", ">Toate<"],
  [">Banners<", ">Bannere<"],
  [">Textiles<", ">Textile<"],
  ["Have a project in mind?", "Ai un proiect în minte?"],
  ["Send us your files and get a free quote within the hour. No minimum order required.", "Trimite-ne fișierele și primești o ofertă gratuită în decurs de o oră. Fără comandă minimă."],
  ["Request a Free Quote", "Cere o ofertă gratuită"],
  ["Screen 5 — Equipment · 12-col grid", "Ecran 5 — Echipamente · grid 12 coloane"],
  ["Our Technology", "Tehnologia noastră"],
  ["Professional-grade equipment", "Echipamente profesionale"],
  ["We invest in industry-leading machines to deliver the best print quality, consistency, and speed.", "Investim în echipamente de top pentru a oferi cea mai bună calitate, consistență și viteză de producție."],
  ["Large Format Printer", "Printer large format"],
  ["Cutter Plotter", "Plotter de tăiere"],
  ["DTF Printer", "Printer DTF"],
  ["Heat Press", "Presă termică"],
  ["Laser Printer", "Printer laser"],
  ["Machine Photo", "Foto echipament"],
  ["Max width: 1341mm (134cm)", "Lățime maximă: 1341 mm (134 cm)"],
  ["Eco-solvent inks", "Cerneluri eco-solvent"],
  ["High-speed production mode", "Mod de producție rapid"],
  ["Indoor & outdoor prints", "Printuri pentru interior și exterior"],
  ["Precision contour cutting", "Tăiere de contur precisă"],
  ["1300mm cutting width", "Lățime de tăiere 1300 mm"],
  ["Vinyl, stickers, decals", "Vinyl, stickere, decaluri"],
  ["Print & cut workflow", "Flux integrat print și tăiere"],
  ["Hot & cold lamination", "Laminare la cald și la rece"],
  ["UV & scratch protection", "Protecție UV și anti-zgâriere"],
  ["Matte or gloss finish", "Finisaj mat sau lucios"],
  ["Direct-to-film technology", "Tehnologie direct-to-film"],
  ["Vibrant textile prints", "Print textil vibrant"],
  ["Any fabric color", "Orice culoare de material"],
  ["Wash-resistant results", "Rezultate rezistente la spălare"],
  ["Consistent heat & pressure", "Căldură și presiune constante"],
  ["Fast print speeds", "Viteză mare de printare"],
  ["Sharp text & graphics", "Text și grafică clare"],
  ["Screen 6 — About · 12-col grid", "Ecran 6 — Despre · grid 12 coloane"],
  ["About Marand", "Despre Marand"],
  ["Your local print partner", "Partenerul tău local pentru print"],
  ["Marand is a professional print shop equipped with the latest large format and textile printing technology. Whether you need a single canvas print or a thousand stickers, we deliver quality results with fast turnaround.", "Marand este un print shop profesionist, echipat cu tehnologie modernă pentru print large format și textile. Fie că ai nevoie de un singur canvas sau de o mie de stickere, livrăm rezultate de calitate, rapid."],
  ["We work with businesses, agencies, event organizers, artists, and individuals — anyone who needs their ideas printed beautifully.", "Lucrăm cu afaceri, agenții, organizatori de evenimente, artiști și persoane fizice — cu oricine are nevoie să își transforme ideile în printuri reușite."],
  ["Shop Interior Photo", "Foto interior shop"],
  ["Avg Turnaround", "Timp mediu de execuție"],
  ["Order Quantity", "Cantitate minimă"],
  ["No min", "Fără minim"],
  ["What Our Clients Say", "Ce spun clienții"],
  ["Excellent quality and incredibly fast. Our event banners looked amazing and were ready in under 24 hours.", "Calitate excelentă și foarte rapid. Bannerele pentru eveniment au arătat impecabil și au fost gata în mai puțin de 24 de ore."],
  ["Event Manager, Local Festival", "Manager eveniment, festival local"],
  ["We order stickers and t-shirts regularly. The colors are always spot-on and the team is super helpful.", "Comandăm constant stickere și tricouri. Culorile ies mereu foarte bine, iar echipa este foarte implicată."],
  ["Small Business Owner", "Proprietar mic business"],
  ["The canvas prints for our gallery exhibition were gallery-quality. Couldn't tell them from original paintings.", "Printurile pe canvas pentru expoziția noastră au fost de nivel gallery. Aproape că nu le puteai deosebi de picturile originale."],
  ["Local Artist", "Artist local"],
  ["Screen 7 — Contact · 12-col grid", "Ecran 7 — Contact · grid 12 coloane"],
  ["Get in Touch", "Ia legătura cu noi"],
  ["Request a quote or visit our shop", "Cere o ofertă sau vizitează shopul"],
  ["Send us your files and requirements — we'll get back to you with a quote within the hour during business hours.", "Trimite-ne fișierele și cerințele tale — îți răspundem cu o ofertă în decurs de o oră în timpul programului."],
  [">Phone<", ">Telefon<"],
  [">Address<", ">Adresă<"],
  ["Street Name, Nr. XX<br>City, Romania", "Numele străzii, nr. XX<br>Oraș, România"],
  ["Working Hours", "Program"],
  ["Mon–Fri: 9:00 – 18:00<br>Sat: 10:00 – 14:00", "Lun–Vin: 9:00 – 18:00<br>Sâm: 10:00 – 14:00"],
  ["Google Maps Embed", "Embed Google Maps"],
  [">Name<", ">Nume<"],
  ['placeholder="Your name"', 'placeholder="Numele tău"'],
  ["Product Type", "Tip produs"],
  ["Select a product...", "Selectează un produs..."],
  ["Canvas Print", "Print pe canvas"],
  ["Stickers / Vinyl Decals", "Stickere / autocolant vinyl"],
  ["Flyers / Business Cards", "Flyere / cărți de vizită"],
  ["Other", "Altul"],
  ["Size / Dimensions", "Dimensiune"],
  ['placeholder="e.g. 200x100 cm"', 'placeholder="ex. 200x100 cm"'],
  [">Quantity<", ">Cantitate<"],
  ['placeholder="e.g. 50 pieces"', 'placeholder="ex. 50 bucăți"'],
  ["Project Details", "Detalii proiect"],
  ['placeholder="Tell us about your project — material preferences, finishing, deadline..."', 'placeholder="Spune-ne despre proiect — preferințe de material, finisaje, termen de livrare..."'],
  ["Drag & drop your files here or click to upload", "Trage fișierele aici sau dă click pentru upload"],
  ["PDF, AI, EPS, PSD, PNG, JPG — max 50MB", "PDF, AI, EPS, PSD, PNG, JPG — max. 50 MB"],
  ["Send Quote Request", "Trimite cererea de ofertă"],
  ["Professional print shop — large format, banners, canvas, stickers, textiles, and more. Quality printing with fast turnaround.", "Print shop profesionist — large format, bannere, canvas, stickere, textile și multe altele. Calitate și execuție rapidă."],
  ["About Us", "Despre noi"],
  ["Mon–Fri: 9–18", "Lun–Vin: 9–18"],
  ["All rights reserved.", "Toate drepturile rezervate."],
  ["Terms & Conditions · Privacy Policy", "Termeni și condiții · Politica de confidențialitate"]
])

replace_all("#{ROOT}/marand-quote-ro.html", common_rewire + [
  ['<html lang="en">', '<html lang="ro">'],
  ["<title>Marand — Request a Quote</title>", "<title>Marand — Cere ofertă</title>"],
  ["Wireframe — Quote Page", "Wireframe — Pagina de ofertă"],
  [">Home<", ">Acasă<"],
  [">Products<", ">Produse<"],
  [">Gallery<", ">Galerie<"],
  [">How It Works<", ">Cum funcționează<"],
  [">Quote<", ">Ofertă<"],
  [">Request a Quote<", ">Cere ofertă<"],
  ["Quote Page — Conversion Flow", "Pagina ofertă — flux de conversie"],
  ["Brief the project once, get the right recommendation faster", "Descrie proiectul o singură dată și primești mai rapid recomandarea potrivită"],
  ["This page turns the site into an actual lead flow. It helps clients define the product type, quantity, timing, artwork status, and contact details without forcing them to browse back and forth between pages.", "Această pagină transformă site-ul într-un flux real de lead-uri. Îi ajută pe clienți să definească tipul de produs, cantitatea, termenul, stadiul graficii și datele de contact fără să se întoarcă între pagini."],
  ["Target reply for simple jobs", "Timp țintă de răspuns pentru lucrări simple"],
  ["No minimum", "Fără minim"],
  ["From one piece to bulk", "De la o singură bucată la volum"],
  ["File check", "Verificare fișier"],
  ["Artwork support included", "Suport pentru grafică inclus"],
  ["Delivery or pickup", "Livrare sau ridicare"],
  ["Flexible fulfillment", "Predare flexibilă"],
  ["Project Brief", "Brief de proiect"],
  ["Request a quote", "Cere ofertă"],
  ["This form is still a wireframe, but the structure is ready for a future form backend or email workflow. The fields are organized to reduce vague quote requests and help Marand qualify jobs immediately.", "Acest formular este încă un wireframe, dar structura este pregătită pentru un backend sau un flux pe email. Câmpurile sunt organizate pentru a reduce cererile vagi și pentru a ajuta Marand să califice rapid lucrările."],
  ["Product Category", "Categorie produs"],
  ["Needed By", "Termen dorit"],
  ["Estimated Quantity", "Cantitate estimată"],
  ["Budget Range", "Buget estimat"],
  ["Need recommendation", "Am nevoie de recomandare"],
  ["As soon as possible", "Cât mai curând posibil"],
  ["Within 2-3 days", "În 2-3 zile"],
  ["Within 1 week", "În 1 săptămână"],
  ["Flexible timing", "Termen flexibil"],
  ["Project Details", "Detalii proiect"],
  ["Describe the product, size, material preference, finishing, installation needs, and any context that affects the quote.", "Descrie produsul, dimensiunea, preferința de material, finisajele, nevoia de montaj și orice context care influențează oferta."],
  ["Artwork Status", "Stadiul graficii"],
  ["Print-ready file available", "Fișier pregătit pentru print"],
  ["The client already has artwork and mainly needs pricing, size confirmation, or production guidance.", "Clientul are deja grafica și are nevoie în principal de preț, confirmarea dimensiunii sau ghidaj pentru producție."],
  ["Need design support", "Am nevoie de suport de design"],
  ["The client needs help adapting, correcting, or creating the artwork before production.", "Clientul are nevoie de ajutor pentru adaptarea, corectarea sau crearea graficii înainte de producție."],
  ["Upload Area", "Zonă de upload"],
  ["Drag files here or click to upload", "Trage fișierele aici sau dă click pentru upload"],
  ["This is a wireframe zone for future upload behavior and file validation.", "Aceasta este o zonă wireframe pentru viitorul comportament de upload și validarea fișierelor."],
  [">Name<", ">Nume<"],
  ['placeholder="Your full name"', 'placeholder="Numele tău complet"'],
  [">Company<", ">Companie<"],
  ['placeholder="Company or brand name"', 'placeholder="Numele companiei sau al brandului"'],
  [">Phone<", ">Telefon<"],
  ["Send Quote Request", "Trimite cererea de ofertă"],
  ["Back to Products", "Înapoi la produse"],
  ["Before You Send", "Înainte să trimiți"],
  ["What helps Marand quote faster", "Ce ajută Marand să ofere mai rapid o estimare"],
  ["Exact or approximate dimensions, especially for banners, signage, or wall graphics.", "Dimensiuni exacte sau aproximative, mai ales pentru bannere, semnalistică sau grafică de perete."],
  ["Quantity and whether this is a one-time run or repeat production.", "Cantitatea și dacă este o lucrare unică sau una recurentă."],
  ["Material preference if you already know it, or note that you want a recommendation.", "Preferința de material dacă o cunoști deja sau menționează că vrei o recomandare."],
  ["Artwork status: ready to print, needs correction, or needs design from scratch.", "Stadiul graficii: gata de print, necesită corecții sau trebuie făcută de la zero."],
  ["Deadline and whether installation or delivery is needed.", "Deadline-ul și dacă este nevoie de montaj sau livrare."],
  ["Response Snapshot", "Rezumat ofertă"],
  ["Typical quote factors", "Factori tipici care influențează oferta"],
  ["Format and dimensions", "Format și dimensiuni"],
  ["One-off vs batch", "Unicat vs. lot"],
  ["Paper, vinyl, canvas, textile", "Hârtie, vinyl, canvas, textil"],
  ["Lamination, cut, frame, install", "Laminare, tăiere, ramă, montaj"],
  ["Quote flow for the improved site", "Fluxul de ofertare pentru versiunea îmbunătățită a site-ului"],
  ["Client chooses a product", "Clientul alege produsul"],
  ["From the products page, gallery, or homepage CTA.", "Din pagina de produse, galerie sau CTA-ul din homepage."],
  ["Client submits details", "Clientul trimite detaliile"],
  ["Quantity, format, deadline, files, and contact info arrive in one structured request.", "Cantitatea, formatul, termenul, fișierele și datele de contact ajung într-o singură cerere structurată."],
  ["Marand reviews feasibility", "Marand verifică fezabilitatea"],
  ["Material, print method, finishing, and design support can be scoped immediately.", "Materialul, metoda de print, finisajele și suportul de design pot fi estimate imediat."],
  ["Quote is sent back", "Oferta este trimisă"],
  ["Clear recommendation, estimated turnaround, and next-step confirmation.", "Recomandare clară, termen estimat și confirmarea pașilor următori."],
  ["Professional print shop with a cleaner quote flow across large format, banners, canvas, stickers, textiles, and small-format jobs.", "Print shop profesionist cu un flux de ofertare mai clar pentru lucrări large format, bannere, canvas, stickere, textile și printuri de mici dimensiuni."],
  [">Pages<", ">Pagini<"],
  [">Actions<", ">Acțiuni<"],
  ["Browse Products", "Vezi produsele"],
  ["See Projects", "Vezi proiectele"],
  ["All rights reserved.", "Toate drepturile rezervate."],
  ["Terms &amp; Conditions · Privacy Policy", "Termeni &amp; condiții · Politica de confidențialitate"]
])

replace_all("#{ROOT}/marand-products-ro.html", common_rewire + [
  ['<html lang="en">', '<html lang="ro">'],
  ["<title>Marand — Products</title>", "<title>Marand — Produse</title>"],
  ["Wireframe — Products Page", "Wireframe — Pagina de produse"],
  [">Home<", ">Acasă<"],
  [">Products<", ">Produse<"],
  [">How It Works<", ">Cum funcționează<"],
  [">Gallery<", ">Galerie<"],
  [">Equipment<", ">Echipamente<"],
  [">About<", ">Despre<"],
  [">Request a Quote<", ">Cere ofertă<"],
  ["Products Page — Header", "Pagina de produse — antet"],
  [">Products</strong>", ">Produse</strong>"],
  ["Our Products", "Produsele noastre"],
  ["Everything we print — from a single business card to a 10-meter outdoor banner. Browse categories below or", "Tot ce printăm — de la o singură carte de vizită până la un banner exterior de 10 metri. Explorează categoriile de mai jos sau"],
  ["request a custom quote", "cere o ofertă personalizată"],
  [">Banners & Mesh<", ">Bannere și mesh<"],
  [">Canvas Prints<", ">Printuri pe canvas<"],
  [">Stickers & Vinyl<", ">Stickere și vinyl<"],
  [">T-Shirts & Textiles<", ">Tricouri și textile<"],
  [">Small Format Prints<", ">Printuri format mic<"],
  ["Large Format Prints", "Printuri large format"],
  ["High-resolution prints up to 134cm wide on a variety of media. Ideal for posters, signage, photo enlargements, art reproductions, trade show graphics, and POS displays. Printed on the <strong>MUTOH XPJ-1341 SR PRO</strong> with eco-solvent inks for vivid, durable color.", "Printuri de înaltă rezoluție de până la 134 cm lățime pe diverse materiale. Ideale pentru postere, semnalistică, fotografii mărite, reproduceri de artă, grafică pentru expoziții și display-uri POS. Printate pe <strong>MUTOH XPJ-1341 SR PRO</strong> cu cerneluri eco-solvent pentru culori vii și rezistente."],
  ["Most Popular", "Cel mai popular"],
  ["Photo Paper Poster", "Poster pe hârtie foto"],
  ["Glossy or matte photo paper. Perfect for indoor posters, photo prints, and retail graphics.", "Hârtie foto lucioasă sau mată. Perfectă pentru postere de interior, printuri foto și grafică de retail."],
  ["200g Photo Paper (Glossy / Matte)", "Hârtie foto 200g (lucioasă / mată)"],
  ["Max Width", "Lățime maximă"],
  ["Resolution", "Rezoluție"],
  ["Use", "Utilizare"],
  [">Indoor<", ">Interior<"],
  ["Popular Sizes", "Dimensiuni populare"],
  ["Custom Size", "Dimensiune personalizată"],
  ["Self-Adhesive Vinyl", "Vinyl autoadeziv"],
  ["Sticker-backed vinyl for wall graphics, window displays, floor decals, and vehicle panels.", "Vinyl autoadeziv pentru grafică de perete, vitrine, stickere de podea și panouri auto."],
  ["Self-adhesive vinyl (white / clear)", "Vinyl autoadeziv (alb / transparent)"],
  ["Lamination", "Laminare"],
  ["Optional (gloss / matte)", "Opțională (lucioasă / mată)"],
  ["Indoor & Outdoor (3–5 yr)", "Interior și exterior (3–5 ani)"],
  ["Common Uses", "Utilizări frecvente"],
  ["Wall Decals", "Decaluri de perete"],
  ["Window Graphics", "Grafică pentru vitrine"],
  ["Floor Stickers", "Stickere de podea"],
  ["Backlit Film", "Film backlit"],
  ["Translucent film for lightboxes. Vibrant colors glow when back-illuminated — ideal for retail and airports.", "Film translucid pentru casete luminoase. Culorile devin intense când sunt iluminate din spate — ideal pentru retail și aeroporturi."],
  ["Backlit PET film", "Film PET backlit"],
  ["High translucency", "Transparență ridicată"],
  ["Lightboxes, displays", "Casete luminoase, display-uri"],
  ["Finishing Options for Large Format", "Opțiuni de finisare pentru large format"],
  ["Gloss or matte lamination (scratch + UV protection)", "Laminare lucioasă sau mată (protecție UV și anti-zgâriere)"],
  ["Mounting on foam board (3mm, 5mm, 10mm)", "Cașerare pe foam board (3 mm, 5 mm, 10 mm)"],
  ["Mounting on Dibond / aluminium composite", "Montaj pe Dibond / aluminiu compozit"],
  ["Grommets / eyelets for hanging", "Capse / inele pentru agățare"],
  ["Hem and pole pocket finishing", "Tiv și buzunar pentru bară"],
  ["Contour cutting to custom shapes", "Tăiere de contur în forme personalizate"],
  ["Roll delivery (unmounted)", "Livrare la rolă (nemontat)"],
  ["Framing (wood or aluminium)", "Înrămare (lemn sau aluminiu)"],
  ["Durable outdoor banners for events, construction sites, storefronts, and exhibitions. PVC flex and mesh options with hemming, eyelets, and optional lamination. Printed on the <strong>MUTOH XPJ-1341 SR PRO</strong>, finished with the <strong>Flexa X-Pro 160</strong> laminator.", "Bannere rezistente pentru exterior, potrivite pentru evenimente, șantiere, vitrine și expoziții. Opțiuni din PVC flex și mesh cu tiv, capse și laminare opțională. Printate pe <strong>MUTOH XPJ-1341 SR PRO</strong> și finisate cu laminatorul <strong>Flexa X-Pro 160</strong>."],
  ["PVC Vinyl Banner", "Banner PVC din vinyl"],
  ["Heavy-duty 440g PVC banner — the industry standard for outdoor signage and event graphics.", "Banner PVC heavy-duty 440g — standardul industriei pentru semnalistică exterioară și grafică de eveniment."],
  ["440g PVC Flex (Frontlit)", "PVC Flex 440g (frontlit)"],
  ["Hemmed + eyelets (every 50cm)", "Tivuit + capse (la fiecare 50 cm)"],
  ["Durability", "Durabilitate"],
  ["Outdoor 2–3 years", "Exterior 2–3 ani"],
  ["Common Sizes", "Dimensiuni uzuale"],
  ["Mesh Banner", "Banner mesh"],
  ["Wind-Resistant", "Rezistent la vânt"],
  ["Perforated mesh with micro-holes that let wind pass through — perfect for fences, scaffolding, and building wraps.", "Material mesh perforat cu micro-găuri care lasă vântul să treacă — perfect pentru garduri, schele și fațade de clădiri."],
  ["PVC Mesh (perforated)", "PVC Mesh (perforat)"],
  ["Wind", "Vânt"],
  ["Wind-through design", "Design care lasă vântul să treacă"],
  ["Outdoor 1–2 years", "Exterior 1–2 ani"],
  ["Complete Kit", "Kit complet"],
  ["Portable retractable banner stand — includes print + aluminium stand + carry bag. Sets up in seconds.", "Sistem retractabil portabil — include print, stand din aluminiu și geantă de transport. Se montează în câteva secunde."],
  ["Print Size", "Dimensiune print"],
  ["Stand", "Stand"],
  ["Aluminium retractable", "Aluminiu retractabil"],
  ["Includes", "Include"],
  ["Print + stand + bag", "Print + stand + geantă"],
  ["Events, expos, lobbies", "Evenimente, expoziții, lobby-uri"],
  ["Banner Finishing Options", "Opțiuni de finisare pentru bannere"],
  ["Hemmed edges (welded or sewn) for extra strength", "Margini tivuite (sudate sau cusute) pentru rezistență suplimentară"],
  ["Metal eyelets / grommets every 50cm or custom spacing", "Capse metalice la 50 cm sau la distanță personalizată"],
  ["Pole pockets (top, bottom, or sides) for hanging systems", "Buzunare pentru bare (sus, jos sau lateral) pentru sisteme de prindere"],
  ["Velcro strips for frame mounting", "Benzi velcro pentru montaj pe cadru"],
  ["Joining / welding for banners wider than 134cm", "Lipire / sudură pentru bannere mai late de 134 cm"],
  ["Gallery-quality canvas prints on premium cotton canvas, stretched on solid wood frames. Perfect for art reproductions, photography, home decor, and gifts. Printed on the <strong>MUTOH XPJ-1341 SR PRO</strong> with archival eco-solvent inks.", "Printuri pe canvas de calitate gallery, pe pânză premium din bumbac, întinse pe rame din lemn masiv. Potrivite pentru reproduceri de artă, fotografie, decor interior și cadouri. Printate pe <strong>MUTOH XPJ-1341 SR PRO</strong> cu cerneluri eco-solvent arhivabile."],
  ["Single Canvas", "Canvas simplu"],
  ["One image, one frame. Classic gallery look.", "O imagine, o ramă. Aspect clasic de galerie."],
  ["Multi-Panel / Split", "Multipanou / split"],
  ["Image split across 2–5 panels for dramatic effect.", "Imagine împărțită în 2–5 panouri pentru un efect vizual puternic."],
  ["Panoramic Canvas", "Canvas panoramic"],
  ["Wide format for landscapes and cityscapes.", "Format lat pentru peisaje și panorame urbane."],
  ["Square Canvas", "Canvas pătrat"],
  ["Instagram-friendly square format prints.", "Printuri în format pătrat, ideale pentru imagini de tip Instagram."],
  ["Canvas Specifications", "Specificații canvas"],
  ["Premium cotton, 380g", "Bumbac premium, 380g"],
  ["Frame", "Ramă"],
  ["Solid pine wood, 2cm or 4cm depth", "Lemn masiv de pin, adâncime 2 cm sau 4 cm"],
  ["Inks", "Cerneluri"],
  ["Eco-solvent, fade-resistant", "Eco-solvent, rezistente la decolorare"],
  ["Edges", "Margini"],
  ["Mirrored, wrapped, or white", "Oglindite, wrapped sau albe"],
  ["Hanging", "Prindere"],
  ["Ready-to-hang (hardware included)", "Gata de agățat (accesorii incluse)"],
  ["Max Size", "Dimensiune maximă"],
  ["Standard Sizes", "Dimensiuni standard"],
  ["Frame Depth", "Adâncime ramă"],
  ["2 cm (Standard)", "2 cm (standard)"],
  ["4 cm (Gallery)", "4 cm (gallery)"],
  ["Custom stickers, vinyl decals, window graphics, and cut lettering. Printed on the <strong>MUTOH XPJ-1341 SR PRO</strong> and precision-cut with the <strong>Mutoh ValueCut II 1300</strong>. Optional lamination on the <strong>Flexa X-Pro 160</strong> for outdoor durability.", "Stickere personalizate, autocolant vinyl, grafică pentru geamuri și litere decupate. Printate pe <strong>MUTOH XPJ-1341 SR PRO</strong> și tăiate cu precizie pe <strong>Mutoh ValueCut II 1300</strong>. Laminare opțională pe <strong>Flexa X-Pro 160</strong> pentru rezistență la exterior."],
  ["Printed & Die-Cut Stickers", "Stickere printate și decupate"],
  ["Full-color printed stickers cut to any custom shape. Laminated for scratch and weather resistance.", "Stickere printate full color, decupate în orice formă. Laminare pentru rezistență la zgârieturi și intemperii."],
  ["White vinyl + lamination", "Vinyl alb + laminare"],
  ["Cutting", "Tăiere"],
  ["Contour / die-cut to shape", "Contur / decupare în formă"],
  ["Min Size", "Dimensiune minimă"],
  ["Popular For", "Populare pentru"],
  ["Logo stickers", "Stickere logo"],
  ["Product labels", "Etichete produs"],
  ["Laptop decals", "Decaluri laptop"],
  ["Cut Vinyl Lettering & Shapes", "Litere și forme din vinyl decupat"],
  ["Single-color vinyl cut to your text, logo, or shape. No background — clean, professional look for glass, walls, and vehicles.", "Vinyl într-o singură culoare, decupat după text, logo sau formă. Fără fundal — aspect curat și profesionist pentru sticlă, pereți și vehicule."],
  ["Colors", "Culori"],
  ["50+ solid colors", "50+ culori pline"],
  ["Application", "Aplicare"],
  ["Transfer tape included", "Folie de transfer inclusă"],
  ["5–7 years outdoor", "5–7 ani la exterior"],
  ["Window & One-Way Vision", "Grafică pentru geam și one-way vision"],
  ["Perforated one-way vision film — full graphics on the outside, see-through from inside. Plus frosted, clear, and opaque options.", "Folie perforată one-way vision — grafică completă la exterior, vizibilitate din interior. Disponibilă și în variante frost, clară sau opacă."],
  ["Types", "Tipuri"],
  ["One-way vision / frosted / clear", "One-way vision / frost / transparent"],
  ["Install", "Montaj"],
  ["Instructions included", "Instrucțiuni incluse"],
  ["Storefronts, vehicles, offices", "Vitrine, vehicule, birouri"],
  ["Sticker & Vinyl Add-Ons", "Opțiuni extra pentru stickere și vinyl"],
  ["Gloss or matte lamination for extra protection and premium feel", "Laminare lucioasă sau mată pentru protecție și aspect premium"],
  ["Kiss-cut on sheets (peel-off sticker sheets)", "Tăiere kiss-cut pe coli (coli de stickere)"],
  ["Application tape / transfer tape included with all cut vinyl", "Folie de transfer inclusă la toate lucrările din vinyl decupat"],
  ["Bulk pricing available — ask for quantity discounts on 100+ pieces", "Prețuri pentru volum disponibile — cere discounturi pentru 100+ bucăți"],
  ["Custom printed garments using DTF (Direct-to-Film) technology. Printed on the <strong>DTF XPD 924</strong> and heat-pressed with the <strong>LOPTUS LTS 38</strong>. Vivid, wash-resistant prints on any color fabric — from single pieces to bulk orders.", "Articole textile personalizate folosind tehnologia DTF (Direct-to-Film). Printate pe <strong>DTF XPD 924</strong> și presate termic cu <strong>LOPTUS LTS 38</strong>. Printuri vii și rezistente la spălare pe orice culoare de material — de la o singură bucată la comenzi mari."],
  ["Custom T-Shirt", "Tricou personalizat"],
  ["Your design printed on a quality cotton or cotton-blend t-shirt. Any color garment, full-color print.", "Designul tău printat pe un tricou de calitate din bumbac sau amestec de bumbac. Orice culoare de tricou, print full color."],
  ["Method", "Metodă"],
  ["Print Area", "Suprafață de print"],
  ["Fabric", "Material textil"],
  ["Cotton, polyester, blends", "Bumbac, poliester, mixuri"],
  ["Wash", "Spălare"],
  ["60°C machine washable", "Spălare la mașină până la 60°C"],
  ["Options", "Opțiuni"],
  ["Print only (bring your shirt)", "Doar print (aduci tu tricoul)"],
  ["T-shirt included", "Tricou inclus"],
  ["Workwear & Uniforms", "Haine de lucru și uniforme"],
  ["Branded polos, hoodies, aprons, and jackets with your company logo. Consistent results across large orders.", "Polo-uri, hanorace, șorțuri și jachete branduite cu logo-ul companiei. Rezultate consistente pentru comenzi mari."],
  ["Items", "Articole"],
  ["Polos, hoodies, jackets, aprons", "Polo-uri, hanorace, jachete, șorțuri"],
  ["Logo + name / number", "Logo + nume / număr"],
  ["Min Order", "Comandă minimă"],
  ["Bulk", "Volum"],
  ["Volume discounts available", "Discounturi pentru volum disponibile"],
  ["Bags, Caps & More", "Sacoșe, șepci și altele"],
  ["Tote bags, caps, cushion covers, and other textile items with custom DTF prints.", "Sacoșe tote, șepci, fețe de pernă și alte articole textile cu print DTF personalizat."],
  ["Tote bags, caps, cushions", "Sacoșe tote, șepci, perne"],
  ["Full color, any garment color", "Full color, pe orice culoare de material"],
  ["Feel", "Textură"],
  ["Soft, flexible finish", "Finisaj moale și flexibil"],
  ["Why DTF Printing?", "De ce print DTF?"],
  ["Works on any fabric color — dark, light, patterned", "Funcționează pe orice culoare de material — închis, deschis sau imprimat"],
  ["Full-color prints with fine detail and gradients", "Printuri full color cu detalii fine și degradeuri"],
  ["Excellent wash resistance (60°C)", "Rezistență excelentă la spălare (60°C)"],
  ["Soft, flexible feel — no heavy \"plasticky\" layer", "Aspect moale și flexibil — fără strat gros, plasticos"],
  ["No minimum order — from 1 piece to 1000+", "Fără comandă minimă — de la 1 bucată la 1000+"],
  ["Small Format Prints", "Printuri format mic"],
  ["Quick-turn marketing materials and business essentials. Printed on the <strong>Ricoh MC2000 A3</strong> color laser for crisp text, sharp graphics, and consistent color. From business cards to A3 posters.", "Materiale de marketing cu execuție rapidă și esențiale pentru business. Printate pe <strong>Ricoh MC2000 A3</strong> color laser pentru text clar, grafică precisă și culori consistente. De la cărți de vizită la postere A3."],
  ["Business Cards", "Cărți de vizită"],
  ["350g cardstock, single or double-sided, optional lamination.", "Carton 350g, față-verso sau simplu, laminare opțională."],
  ["Flyers & Leaflets", "Flyere și pliante"],
  ["A5 / A4 / A3 — 135g to 250g, glossy or matte.", "A5 / A4 / A3 — între 135g și 250g, lucios sau mat."],
  ["Brochures", "Broșuri"],
  ["Bi-fold or tri-fold, 170g glossy paper, full color.", "Plieri în 2 sau 3, hârtie lucioasă 170g, full color."],
  ["Menus & Price Lists", "Meniuri și liste de preț"],
  ["A4 / A3 laminated or cardstock. Restaurant-ready.", "A4 / A3, laminate sau carton. Gata pentru restaurant."],
  ["Small Format Options", "Opțiuni pentru format mic"],
  ["Paper Weights", "Gramaje hârtie"],
  ["80g (Standard)", "80g (standard)"],
  ["135g (Flyer)", "135g (flyer)"],
  ["170g (Brochure)", "170g (broșură)"],
  ["250g (Card)", "250g (card)"],
  ["350g (Business Card)", "350g (carte de vizită)"],
  ["Sizes", "Dimensiuni"],
  ["85×55 mm (card)", "85×55 mm (carte de vizită)"],
  ["Not sure what you need?", "Nu ești sigur ce ai nevoie?"],
  ["Send us your project details and we'll recommend the best product, material, and size for your budget.", "Trimite-ne detaliile proiectului și îți recomandăm produsul, materialul și dimensiunea potrivită pentru bugetul tău."],
  ["Request a Free Quote", "Cere o ofertă gratuită"],
  ["Professional print shop — large format, banners, canvas, stickers, textiles, and more.", "Print shop profesionist — large format, bannere, canvas, stickere, textile și multe altele."],
  ["About Us", "Despre noi"],
  ["All rights reserved.", "Toate drepturile rezervate."],
  ["Terms & Conditions · Privacy Policy", "Termeni și condiții · Politica de confidențialitate"]
])

replace_all("#{ROOT}/marand-gallery-ro.html", common_rewire + [
  ['<html lang="en">', '<html lang="ro">'],
  ["<title>Marand — Gallery</title>", "<title>Marand — Galerie</title>"],
  ["Wireframe — Gallery Page", "Wireframe — Pagina galerie"],
  [">Home<", ">Acasă<"],
  [">Products<", ">Produse<"],
  [">How It Works<", ">Cum funcționează<"],
  [">Gallery<", ">Galerie<"],
  [">Equipment<", ">Echipamente<"],
  [">About<", ">Despre<"],
  [">Request a Quote<", ">Cere ofertă<"],
  ["Gallery Page — Header", "Pagina galerie — antet"],
  [">Gallery</strong>", ">Galerie</strong>"],
  ["Print projects that feel built, not generic", "Proiecte de print care par construite cu intenție, nu generice"],
  ["A curated view of banners, retail graphics, canvas work, stickers, textile printing, and small-format pieces. Each project block combines a visual reference with the production details that matter to clients reviewing quality.", "O selecție atentă de bannere, grafică de retail, lucrări pe canvas, stickere, print textil și piese de format mic. Fiecare bloc combină o referință vizuală cu detaliile de producție care contează pentru clienți."],
  ["Core Categories", "Categorii principale"],
  ["Showcased Project Types", "Tipuri de proiect prezentate"],
  ["Indoor + Outdoor", "Interior + exterior"],
  ["Applications", "Aplicații"],
  ["Fast Turnaround", "Execuție rapidă"],
  ["Production Focus", "Focus pe producție"],
  [">All Work<", ">Toate lucrările<"],
  [">Featured<", ">Recomandate<"],
  [">Retail Branding<", ">Branding retail<"],
  [">Events &amp; Signage<", ">Evenimente &amp; semnalistică<"],
  [">Canvas &amp; Decor<", ">Canvas &amp; decor<"],
  [">Vinyl &amp; Stickers<", ">Vinyl &amp; stickere<"],
  [">Textiles<", ">Textile<"],
  [">Small Format<", ">Format mic<"],
  ["Featured Projects", "Proiecte recomandate"],
  ["Hero references for client review", "Referințe hero pentru evaluarea clientului"],
  ["These larger cards show how the gallery page can mix polished imagery with concise production notes. The goal is to help a client understand both the look of the work and the practical delivery details.", "Aceste carduri mari arată cum pagina de galerie poate combina imagini curate cu note scurte despre producție. Scopul este ca clientul să înțeleagă atât aspectul lucrării, cât și detaliile practice de livrare."],
  ["Event Backdrop", "Fundal de eveniment"],
  ["Conference stage wall with sponsor branding", "Perete de scenă pentru conferință cu branding de sponsori"],
  ["PVC flex print · modular install", "Print PVC flex · montaj modular"],
  ["A flagship large-format example showing a branded backdrop built for event photography, sponsor visibility, and clean stage presence. The card can later support client notes, dimensions, or installation instructions.", "Un exemplu reprezentativ de large format care arată un fundal branduit gândit pentru fotografii la eveniment, vizibilitatea sponsorilor și o prezență curată pe scenă. Cardul poate include ulterior note pentru client, dimensiuni sau instrucțiuni de montaj."],
  ["Retail Window", "Vitrină retail"],
  ["Storefront graphics for seasonal campaign", "Grafică de vitrină pentru campanie sezonieră"],
  ["Vinyl application · high street retail", "Aplicare vinyl · retail stradal"],
  ["A retail-focused visual that highlights campaign messaging, visibility from the street, and cohesive branding across glass surfaces and entrance areas.", "Un vizual orientat spre retail care pune accent pe mesajul campaniei, vizibilitatea din stradă și brandingul coerent pe suprafețele vitrate și la intrare."],
  ["Category 01", "Categoria 01"],
  ["Retail branding and window graphics", "Branding retail și grafică pentru vitrine"],
  ["Projects in this category show how Marand can help a shop, showroom, or pop-up location look immediately more polished and visible from outside.", "Proiectele din această categorie arată cum Marand poate face un magazin, showroom sau pop-up să pară imediat mai bine finisat și mai vizibil din exterior."],
  ["Street-facing launch campaign for a boutique storefront", "Campanie de lansare orientată spre stradă pentru o vitrină boutique"],
  ["Full-window vinyl graphics designed to stop foot traffic, frame the entry experience, and communicate the seasonal promotion without blocking natural light too aggressively.", "Grafică integrală pe geam, gândită pentru a atrage privirea, a marca experiența de intrare și a comunica promoția sezonieră fără a bloca prea agresiv lumina naturală."],
  ["Use Case", "Utilizare"],
  ["Store launch", "Lansare magazin"],
  ["Printed vinyl", "Vinyl printat"],
  ["Matte lamination", "Laminare mată"],
  ["Interior retail signage and branded displays", "Semnalistică interioară retail și display-uri branduite"],
  ["In-store display graphics for product storytelling", "Grafică de display pentru prezentarea produselor în magazin"],
  ["This reference card combines mounted prints, directional signage, and branded display surfaces. It works well for demonstrating category signage and campaign cohesion inside the store.", "Acest card de referință combină printuri montate, semnalistică direcțională și suprafețe de display branduite. Funcționează bine pentru a demonstra semnalistica de categorie și coerența campaniei în interiorul magazinului."],
  ["Showroom", "Showroom"],
  ["Rigid mount", "Montaj rigid"],
  ["Category 02", "Categoria 02"],
  ["Events, banners, and wayfinding", "Evenimente, bannere și wayfinding"],
  ["For launches, expos, weddings, conferences, and public activations, this category shows bold surfaces that need to read clearly at distance.", "Pentru lansări, expoziții, nunți, conferințe și activări publice, această categorie arată suprafețe puternice care trebuie să fie lizibile de la distanță."],
  ["Branded event signage and backdrop system", "Semnalistică branduită și sistem de fundal pentru eveniment"],
  [">Events<", ">Evenimente<"],
  ["Backdrop", "Fundal"],
  ["Stage backdrop and sponsor wall for a live event", "Fundal de scenă și perete de sponsori pentru un eveniment live"],
  ["A high-visibility print application with clean logo reproduction, modular sizing, and durable material suitable for installation, teardown, and transport between venues.", "O aplicație de print cu vizibilitate mare, reproducere curată a logo-urilor, dimensiuni modulare și material rezistent potrivit pentru montaj, demontare și transport între locații."],
  ["Conference", "Conferință"],
  ["Eyelets + hem", "Capse + tiv"],
  ["Outdoor event banner and directional signage", "Banner exterior pentru eveniment și semnalistică direcțională"],
  [">Outdoor<", ">Exterior<"],
  ["Directional signage set for crowd movement and visibility", "Set de semnalistică direcțională pentru fluxul mulțimii și vizibilitate"],
  ["This card demonstrates how banner systems and sign panels can support navigation, reinforce branding, and stay legible across larger outdoor environments.", "Acest card demonstrează cum sistemele de bannere și panourile de semnalistică pot susține orientarea, consolida brandingul și rămâne lizibile în medii exterioare ample."],
  ["Festival", "Festival"],
  ["Outdoor durable", "Rezistent la exterior"],
  ["Category 03", "Categoria 03"],
  ["Canvas prints and decorative work", "Printuri pe canvas și lucrări decorative"],
  ["This part of the gallery lets clients review more premium, interior-oriented work: framed canvas, gallery walls, reproduction prints, and decor-ready pieces.", "Această parte a galeriei le permite clienților să analizeze lucrări premium, orientate spre interior: canvas înrămat, pereți de galerie, reproduceri și piese decorative gata de expus."],
  ["Canvas artwork displayed in a gallery-style interior", "Lucrare pe canvas expusă într-un interior de tip galerie"],
  ["Gallery Style", "Stil galerie"],
  ["Large canvas print prepared for gallery presentation", "Print mare pe canvas pregătit pentru expunere tip galerie"],
  ["A premium visual reference for art reproduction and interior decor clients. The page layout leaves room to note frame depth, edge wrap, and print finish options.", "O referință vizuală premium pentru clienții interesați de reproduceri de artă și decor interior. Structura paginii lasă loc pentru notarea adâncimii ramei, wrap-ului pe margini și opțiunilor de finisaj."],
  ["Exhibition", "Expoziție"],
  ["Artist canvas", "Canvas artistic"],
  ["Stretched frame", "Ramă întinsă"],
  ["Framed decorative print in a modern interior", "Print decorativ înrămat într-un interior modern"],
  ["Decor", "Decor"],
  ["Framed Print", "Print înrămat"],
  ["Interior wall print for hospitality or office decor", "Print de perete pentru decor hotelier sau de birou"],
  ["A softer application that shows how Marand can support hotels, offices, and residential interiors with polished printed visuals that complement the space rather than overpower it.", "O aplicație mai subtilă care arată cum Marand poate susține hoteluri, birouri și interioare rezidențiale cu vizualuri printate rafinate, care completează spațiul fără să îl domine."],
  ["Interior decor", "Decor interior"],
  ["Framed option", "Opțiune înrămată"],
  ["Category 04", "Categoria 04"],
  ["Vinyl, decals, and sticker work", "Vinyl, decaluri și stickere"],
  ["These examples help present precision cutting, smaller branded applications, and surfaces where durability and contour quality matter.", "Aceste exemple ajută la prezentarea tăierii precise, a aplicațiilor branduite de dimensiuni mici și a suprafețelor unde contează durabilitatea și calitatea conturului."],
  ["Sticker sheets and vinyl decal production", "Coli de stickere și producție de decaluri din vinyl"],
  ["Batch Production", "Producție în serie"],
  ["Printed sticker sheets for product packaging and merch", "Coli de stickere printate pentru packaging și merch"],
  ["A compact but commercially useful category that can speak to product brands, events, and small businesses needing repeatable sticker batches with clean cutting and consistent color.", "O categorie compactă, dar foarte utilă comercial, care se potrivește brandurilor de produs, evenimentelor și micilor afaceri care au nevoie de loturi repetabile de stickere, cu tăiere curată și culoare consistentă."],
  ["Adhesive vinyl", "Vinyl autoadeziv"],
  ["Contour cut", "Tăiere de contur"],
  ["Vehicle decal application and branded vinyl lettering", "Aplicare de decaluri auto și litere branduite din vinyl"],
  ["Vehicle Graphics", "Grafică auto"],
  ["Vehicle branding with durable exterior vinyl application", "Branding auto cu aplicare de vinyl rezistent la exterior"],
  ["A higher-impact decal use case built around visibility on the road, durable materials, and crisp typography that remains readable on curved surfaces and moving vehicles.", "Un caz de utilizare cu impact mare, construit în jurul vizibilității în trafic, materialelor durabile și unei tipografii clare, care rămâne lizibilă pe suprafețe curbate și vehicule în mișcare."],
  ["Fleet branding", "Branding flotă"],
  ["Exterior vinyl", "Vinyl exterior"],
  ["Category 05", "Categoria 05"],
  ["Textile printing and team apparel", "Print textil și articole pentru echipe"],
  ["The textile section is useful for demonstrating DTF flexibility across staff uniforms, branded merch, event shirts, and smaller custom runs.", "Secțiunea de textile este utilă pentru a demonstra flexibilitatea DTF pe uniforme de staff, merch branduit, tricouri de eveniment și comenzi personalizate mai mici."],
  ["Printed t-shirts displayed on hangers", "Tricouri printate expuse pe umerașe"],
  ["DTF Print", "Print DTF"],
  ["Branded team t-shirts with bold front graphic placement", "Tricouri de echipă branduite, cu grafică frontală puternică"],
  ["A direct example for workwear or promo orders. The layout can support notes on garment type, print size, placement options, and color consistency across multiple sizes.", "Un exemplu direct pentru workwear sau comenzi promoționale. Layoutul poate include note despre tipul de articol, dimensiunea printului, opțiunile de plasare și consistența culorilor pe mai multe mărimi."],
  ["Team apparel", "Articole pentru echipă"],
  ["Cotton blend", "Amestec de bumbac"],
  ["Wash resistant", "Rezistent la spălare"],
  ["Folded textile products and branded merch", "Produse textile împăturite și merch branduit"],
  ["Accessories", "Accesorii"],
  ["Custom tote bags and textile accessories for campaigns", "Sacoșe tote personalizate și accesorii textile pentru campanii"],
  ["This shows how the same section can extend beyond shirts into tote bags, event packs, and branded textile extras that support promotional launches or retail merchandise.", "Acest exemplu arată cum aceeași secțiune poate merge dincolo de tricouri spre sacoșe tote, kituri de eveniment și extra-uri textile branduite care susțin lansări promoționale sau merchandise de retail."],
  ["Promotional merch", "Merch promoțional"],
  ["Canvas textile", "Textil canvas"],
  ["DTF transfer", "Transfer DTF"],
  ["Category 06", "Categoria 06"],
  ["Small-format print pieces", "Piese printate de format mic"],
  ["Cards, flyers, folded menus, handouts, and brochures round out the gallery with practical examples clients may need alongside larger-format work.", "Cărțile de vizită, flyerele, meniurile pliate, materialele de tip handout și broșurile completează galeria cu exemple practice de care clienții pot avea nevoie alături de lucrările de format mare."],
  ["Printed flyers and marketing handouts on a desk", "Flyere printate și materiale de marketing pe birou"],
  ["Campaign Print", "Print de campanie"],
  ["Promotional flyers with strong color coverage and clean trim", "Flyere promoționale cu acoperire bună de culoare și tăiere curată"],
  ["A compact campaign deliverable ideal for local promotions, menus, offers, or event handouts. This card balances the visual example with enough production detail for trust-building.", "Un material compact de campanie, ideal pentru promoții locale, meniuri, oferte sau handout-uri de eveniment. Acest card echilibrează exemplul vizual cu suficiente detalii de producție pentru a construi încredere."],
  ["Local campaign", "Campanie locală"],
  ["Coated stock", "Hârtie cretată"],
  ["Double-sided", "Față-verso"],
  ["Business cards and printed stationery", "Cărți de vizită și papetărie printată"],
  ["Stationery", "Papetărie"],
  ["Business card set with premium tactile finish", "Set de cărți de vizită cu finisaj premium la atingere"],
  ["A useful gallery closer for corporate clients who need essentials: business cards, appointment cards, and small collateral pieces with cleaner finishing and sharper typography.", "Un final de galerie util pentru clienții corporate care au nevoie de piese esențiale: cărți de vizită, carduri de programare și alte materiale mici, cu finisaje curate și tipografie mai bine definită."],
  ["Brand stationery", "Papetărie de brand"],
  ["350g stock", "Carton 350g"],
  ["Soft-touch matte", "Mat soft-touch"],
  ["Client Review Block", "Bloc pentru feedback client"],
  ["This gallery format makes it easier to understand what Marand can actually produce, not just what services are listed.", "Acest format de galerie face mai ușor de înțeles ce poate produce efectiv Marand, nu doar ce servicii sunt listate."],
  ["Suggested testimonial placement for the live site or for stakeholder review during the wireframe phase. This section can later rotate real testimonials or project highlights.", "Poziționare sugerată pentru testimonial pe site-ul live sau pentru review intern în faza de wireframe. Această secțiune poate afișa ulterior testimoniale reale sau proiecte reprezentative."],
  ["Want your project featured like this?", "Vrei ca proiectul tău să fie prezentat așa?"],
  ["Use this page as the reference layout for future real photography, case studies, and finished customer projects. It is already structured around categories, visuals, and concise descriptive copy.", "Folosește această pagină ca layout de referință pentru viitoare fotografii reale, studii de caz și proiecte finalizate pentru clienți. Este deja structurată pe categorii, vizualuri și texte scurte descriptive."],
  ["Professional print shop with gallery-ready visuals across large format, textiles, vinyl, signage, and everyday print products.", "Print shop profesionist cu vizualuri pregătite pentru galerie pentru large format, textile, vinyl, semnalistică și produse de print uzual."],
  [">Pages<", ">Pagini<"],
  [">Categories<", ">Categorii<"],
  ["All rights reserved.", "Toate drepturile rezervate."],
  ["Terms &amp; Conditions · Privacy Policy", "Termeni &amp; condiții · Politica de confidențialitate"]
])

replace_all("#{ROOT}/marand-wireframes-ro.html", [
  ["DTF Technology", "Tehnologie DTF"],
  ["Small Format Prints", "Printuri format mic"],
  ["Banner Photo", "Foto banner"],
  ["Canvas Photo", "Foto canvas"],
  ["Sticker Photo", "Foto stickere"],
  ["T-shirt Photo", "Foto tricou"],
  ["from €12/m²", "de la 12 €/m²"],
  ["from €25", "de la 25 €"],
  ["from €0.50/pc", "de la 0,50 €/buc"],
  ["from €15", "de la 15 €"],
  ["Design Services · 12-col grid", "Servicii de design · grid 12 coloane"],
  ["In-House Design Studio", "Studio de design intern"],
  ["No design? No problem", "Nu ai design? Nicio problemă"],
  ["You don't need a finished file to work with us. Our in-house design team takes your ideas — a sketch on a napkin, a rough concept, or just a vision in your head — and turns them into print-ready artwork.", "Nu ai nevoie de un fișier final ca să lucrezi cu noi. Echipa noastră internă de design îți ia ideile — o schiță pe o hârtie, un concept de bază sau doar o viziune — și le transformă în grafică pregătită pentru print."],
  ["From logo design and branding to event visuals and packaging layouts, we handle every step of the creative process so you get a finished product you're proud of.", "De la logo și branding până la vizualuri pentru evenimente și layout-uri de packaging, gestionăm fiecare etapă a procesului creativ astfel încât să primești un rezultat final de care să fii mulțumit."],
  ["Logo Design", "Design logo"],
  ["Brand Identity", "Identitate de brand"],
  ["Banner & Signage Layout", "Layout pentru bannere și semnalistică"],
  ["Flyer & Brochure Design", "Design pentru flyere și broșuri"],
  ["Social Media Graphics", "Grafică social media"],
  ["T-Shirt & Merch Art", "Design pentru tricouri și merch"],
  ["Vehicle Wrap Design", "Design pentru colantare auto"],
  ["Discuss Your Project", "Discută proiectul tău"],
  ["See Our Work", "Vezi lucrările noastre"],
  ["Lead Designer", "Lead designer"],
  ["14+ Years in the Design Industry", "Peste 14 ani în industria de design"],
  ["Our creative team is led by one of the most experienced designers in the industry. With over 14 years of hands-on experience across branding, print, digital, and packaging design, they bring a level of craft and strategic thinking that elevates every project.", "Echipa noastră creativă este coordonată de unul dintre cei mai experimentați designeri din industrie. Cu peste 14 ani de experiență practică în branding, print, digital și packaging, aduce un nivel de execuție și gândire strategică ce ridică fiecare proiect."],
  ["Whether it's a single business card or a full brand identity system — your project gets the same attention to detail and creative excellence.", "Fie că este vorba despre o singură carte de vizită sau despre un întreg sistem de identitate vizuală, proiectul tău primește aceeași atenție la detalii și aceeași calitate creativă."],
  ["Brief & Concept", "Brief și concept"],
  ["Tell us your idea. We listen, ask the right questions, and define the direction.", "Spune-ne ideea ta. Ascultăm, punem întrebările potrivite și definim direcția."],
  ["Design & Revisions", "Design și revizii"],
  ["We design, you review. Revisions until you're 100% happy.", "Noi desenăm, tu revizuiești. Facem ajustări până ești complet mulțumit."],
  ["Print-Ready Files", "Fișiere pregătite pentru print"],
  ["We prepare files optimized for our machines — correct colors, bleed, and resolution.", "Pregătim fișiere optimizate pentru echipamentele noastre — culori corecte, bleed și rezoluție potrivită."],
  ["Print & Deliver", "Print și livrare"],
  ["From screen to finished product — seamless, fast, and beautiful.", "De la ecran la produs final — clar, rapid și bine executat."],
  ["Canvas (cotton)", "Canvas (bumbac)"],
  ["Stickers", "Stickere"],
  ["Vinyl Stickers — Batch", "Stickere din vinyl — batch"],
  ["Print pe canvas — Gallery", "Print pe canvas — galerie"],
  ["Large Format Print", "Print large format"],
  ["T-Shirts / Textile (DTF)", "Tricouri / textile (DTF)"]
])

replace_all("#{ROOT}/marand-quote-ro.html", [
  ["<strong>1 hour</strong>", "<strong>1 oră</strong>"],
  ["<option>Large Format Prints</option>", "<option>Printuri large format</option>"],
  ["<option>Banners & Mesh</option>", "<option>Bannere și mesh</option>"],
  ["<option>Canvas Prints</option>", "<option>Printuri pe canvas</option>"],
  ["<option>Stickers & Vinyl</option>", "<option>Stickere și vinyl</option>"],
  ["<option>T-Shirts & Textiles</option>", "<option>Tricouri și textile</option>"],
  ["<option>Small Format Prints</option>", "<option>Printuri format mic</option>"],
  ['placeholder="e.g. 50 stickers, 2 banners, 12 shirts"', 'placeholder="ex. 50 stickere, 2 bannere, 12 tricouri"'],
  ["<option>Under €100</option>", "<option>Sub 100 €</option>"],
  ["<option>€100–€300</option>", "<option>100 €–300 €</option>"],
  ["<option>€300–€1000</option>", "<option>300 €–1000 €</option>"],
  ["<strong>Size</strong>", "<strong>Dim.</strong>"],
  ["<strong>Finish</strong>", "<strong>Finisaj</strong>"]
])

replace_all("#{ROOT}/marand-products-ro.html", [
  ['<a href="#large-format" class="active">Large Format</a>', '<a href="#large-format" class="active">Large format</a>'],
  ["Get a Quote", "Cere ofertă"],
  ["Best Seller", "Cel mai vândut"],
  ["Canvas — Single", "Canvas — simplu"],
  ["Canvas — Multi-panel", "Canvas — multipanou"],
  ["Canvas — Panoramic", "Canvas — panoramic"],
  ["Canvas — Square", "Canvas — pătrat"],
  ["<tr><td>Canvas</td><td>Bumbac premium, 380g</td></tr>", "<tr><td>Pânză</td><td>Bumbac premium, 380g</td></tr>"],
  ["Printed Stickers", "Stickere printate"],
  ['<li><a href="#large-format">Large Format</a></li>', '<li><a href="#large-format">Large format</a></li>']
])

replace_all("#{ROOT}/marand-gallery-ro.html", [
  ["Canvas or photo paper", "Canvas sau hârtie foto"],
  ["<span>Stickers</span>", "<span>Stickere</span>"],
  ["<span>Business Cards</span>", "<span>Cărți de vizită</span>"]
])
